[package]
name = "minidesk"
version = "0.1.0"
edition = "2021"

[dependencies]
x11 = "2.21.0"

[[bin]]
name = "minidesk"
path = "src/minidesk/main.rs"

[[bin]]
name = "minidesk-menu"
path = "src/minidesk-menu/main.rs"
